# Generated by Django 5.0.6 on 2024-06-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_travel", "0005_contact"),
        ("app_user", "0002_alter_user_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_user.user"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
            },
        ),
        migrations.CreateModel(
            name="Booking_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("booking_quantity", models.IntegerField(default=1)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_booking.booking",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_travel.tour",
                    ),
                ),
            ],
        ),
    ]
