# Generated by Django 5.0.6 on 2024-06-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_booking", "0001_initial"),
        ("app_user", "0002_alter_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adult_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="children_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("D", "Draft"), ("P", "Paid"), ("C", "Complete")],
                default="D",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_booking.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_user.user"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Booking_Detail",
        ),
    ]
