# Generated by Django 5.0.6 on 2024-06-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_booking",
            "0002_booking_adult_quantity_booking_children_quantity_and_more",
        ),
        ("app_travel", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tour",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_travel.tour",
            ),
            preserve_default=False,
        ),
    ]
