# Generated by Django 5.0.6 on 2024-06-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_booking", "0004_passenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="birthday",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
