# Generated by Django 5.0.6 on 2024-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_booking", "0005_alter_passenger_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
