# Generated by Django 5.0.6 on 2024-06-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_booking", "0006_alter_passenger_birthday"),
        ("app_user", "0002_alter_user_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookingHistory",
            new_name="BookingManager",
        ),
        migrations.AlterModelOptions(
            name="passenger",
            options={"verbose_name_plural": "Thông Tin Hành Khách"},
        ),
    ]
