# Generated by Django 5.0.6 on 2024-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_booking", "0009_alter_booking_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
