# Generated by Django 5.0.6 on 2024-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
