# Generated by Django 5.0.6 on 2024-06-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "Email đã tồn tại."},
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Tên dăng nhập đã tồn tại."},
                max_length=100,
                unique=True,
            ),
        ),
    ]
