# Generated by Django 5.0.6 on 2024-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0006_alter_user_member_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="member_class",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
