# Generated by Django 5.0.6 on 2024-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0007_alter_user_member_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="member_class",
            field=models.CharField(blank=True, default="Hạng Đồng", max_length=150),
        ),
    ]
