# Generated by Django 5.0.6 on 2024-05-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="tours/category/default.jpg", upload_to="tours/category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField(default=0.0)),
                (
                    "image",
                    models.ImageField(
                        default="tours/images/default.png", upload_to="tours/images"
                    ),
                ),
                ("days", models.CharField(max_length=150)),
                ("journey", models.CharField(blank=True, max_length=200)),
                ("transportation", models.CharField(blank=True, max_length=200)),
                ("acommondation", models.CharField(blank=True, max_length=200)),
                ("schedule", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="app_travel.category",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dep_tours",
                        to="app_travel.departure",
                    ),
                ),
            ],
        ),
    ]
