# Generated by Django 5.0.6 on 2024-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="acommondation",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="journey",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="transportation",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
