# Generated by Django 5.0.6 on 2024-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0002_alter_tour_acommondation_alter_tour_journey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=250, unique=True)),
                ("link", models.URLField(null=True)),
                (
                    "image",
                    models.ImageField(
                        default="tours/background-slider/default.png",
                        upload_to="tours/background-slider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("link", models.URLField(null=True)),
                (
                    "image",
                    models.ImageField(
                        default="tours/promotions/default.png",
                        upload_to="tours/promotions",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tour",
            name="booked",
            field=models.IntegerField(default=0),
        ),
    ]
