# Generated by Django 5.0.6 on 2024-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0003_backgroundslider_promotions_tour_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="departure_date",
            field=models.DateField(null=True),
        ),
    ]
