# Generated by Django 5.0.6 on 2024-06-06 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0004_tour_departure_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("subject", models.CharField(max_length=264)),
                ("message", models.TextField()),
                (
                    "created_day",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
