# Generated by Django 5.0.6 on 2024-06-10 07:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_travel", "0005_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="schedule",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
